# Generated by Django 4.2.5 on 2023-10-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
