# Generated by Django 4.2.5 on 2023-10-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_craeted_at_books_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='borrow',
            field=models.IntegerField(null=True),
        ),
    ]
