# Generated by Django 4.2.5 on 2023-10-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0002_rename_craeted_at_books_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, max_length=2, null=True)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='borrowedbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookimage', to='Admin.books')),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowbooks', to='Admin.books')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowstud', to='students.students')),
            ],
        ),
    ]
