# Generated by Django 4.2.5 on 2023-10-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='borrowedbooks',
        ),
    ]
